### PR TITLE
gui setup built in a separate binary

### PR DESCRIPTION
**Pull request by nicolasbauw**
I forget I changed the env var name to OPENWEATHER_LOCATION, before I saw your own changes.

You can build with cargo build, you will have both exectuables:
temp_tray-rs.exe
setup.exe

setup runs but I did not test it, I think it sets the env only for the process, so my bet is that it won't behave as expected once we run the systray program.

### CODE REVIEW

**Comment by Werner1201** [comment]
Ok, Will Merge and Test it.

**Comment by Werner1201** [comment]
Oh well, I tested and it doesn't set the env on the environment variables. I'll search for some libraries if any do what we want. If I don't, I suggest we make the setup create a Folder on the system and store this info in a file inside this installation folder and we can put the program there too

**Comment by Werner1201** [comment]
Or we could use the std::process::Command to set the env vars on the setup we only need to set a check before the execution so we know what OS is running. [here](https://doc.rust-lang.org/std/process/struct.Command.html)

**Comment by nicolasbauw** [comment]
maybe [this crate](https://crates.io/crates/envmnt) could also help.

**Comment by Werner1201** [comment]
I did the process::command it worked

**Comment by Werner1201** [comment]
@nicolasbauw [this crate](https://crates.io/crates/envmnt) seem a more elegant solution. Mine was kinda junky.

**Comment by Werner1201** [comment]
test it, See if you think it's better to use the crate

**Comment by Werner1201** [comment]
Interesting that the crate doesn't adress if it is local variables or if they are stored on the system.

**Comment by Werner1201** [comment]
My whole inspiration is the linux possibilities of making these types of trays without much effort just learning bash.

**Comment by nicolasbauw** [comment]
I did not try the systray crate on linux, I don't have a linux machine right now, but we can try on WSL2 to see if it compiles

**Pull request merged**
