### PR TITLE
Removal of useless reference and dereference

### PR DESCRIPTION
**Pull request by nicolasbauw**
My idea for setting up user API key and location : use a setup program / script which is separate from the systray app itself, which will set the variables in the OS environment variables:

image

### CODE REVIEW

**Comment by Werner1201** [comment]
OK it seems more concise then having it all as the same "program". But are you planning on using the GUI library to make it easier to setup ?

**Comment by Werner1201** [comment]
Should We make a separate project just to set the ENV vars ?

**Comment by Werner1201** [comment]
Or we just publish the setup binary ?

**Comment by Werner1201** [comment]
If we make another project just for the setup we can make it download the binary from the releases here and setup a folder to "install" and add it to the initialization programs on windows.

**Comment by Werner1201** [comment]
Tell me what you think is best and if you want me to make the new repo or you.

**Comment by nicolasbauw** [comment]
[This page](https://doc.rust-lang.org/cargo/guide/project-layout.html) explains how to do it in the same project, I'm currently trying  that to create a setup binary, based on the code you wrote.

**Comment by Werner1201** [comment]
OK,I'll close the pull request when you are done you can make another one

**Pull request merged**
